// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApHdSt-2eOgbCQBFFpgZnZsB3O3hEykEY',
    appId: '1:1037601533196:web:b341d7ce72d7b5ac992d29',
    messagingSenderId: '1037601533196',
    projectId: 'mareks-salon-app',
    authDomain: 'mareks-salon-app.firebaseapp.com',
    storageBucket: 'mareks-salon-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwk75-CPSQ_tjVPBXKkFofiAAYf6nV1Uc',
    appId: '1:1037601533196:android:aa9a75f70a4516e4992d29',
    messagingSenderId: '1037601533196',
    projectId: 'mareks-salon-app',
    storageBucket: 'mareks-salon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZems74iumFCCOp9bn33KU47kZ3nS4ios',
    appId: '1:1037601533196:ios:22e11a4c890b2797992d29',
    messagingSenderId: '1037601533196',
    projectId: 'mareks-salon-app',
    storageBucket: 'mareks-salon-app.firebasestorage.app',
    iosBundleId: 'com.marekssalon.mareksSalon',
  );
}
